"""Paper fidelity: the resource-aware selection knobs (A14-A16) never change default-profile decisions.

``default_profile_decisions.json`` was generated by the pre-resource selection code over the scenarios
below. The scenarios carry surface and runtime metrics, which the default profiles must ignore: every
decision must match the golden record once the new resource fields are dropped.
"""

from __future__ import annotations

import json
from dataclasses import replace
from pathlib import Path
from typing import Any

import pytest

from ci_lab.contracts import (
    ArmResult,
    Edit,
    EvalResult,
    EvaluatorPin,
    TaskScore,
    Violation,
)
from ci_lab.rrsi import stats
from ci_lab.rrsi.params import profile
from ci_lab.rrsi.selection import SelectionInputs, select

GOLDEN = Path(__file__).with_name("default_profile_decisions.json")
PROFILES = ("smoke", "local", "paper")
NEW_ARM_KEYS = {"delta_x", "delta_calls", "delta_wall", "complexity", "calls_per_task", "wall_ms_p50",
                "simplicity_score", "resources"}
NEW_PARAM_KEYS = {"w_x", "x_cap", "calls_cap", "wall_cap", "require_resource_metrics"}

PIN = EvaluatorPin(evaluator_tree="evaltree", judge_model="judge", judge_provider="prov")
CRIT = Violation(rule_id="safety.crit", severity="critical", detail="x")


def _ev(scores: list[float | None], *, tokens: int = 100, calls: int = 4, wall: float = 1000.0,
        complexity: float | None = 100.0, crit: int = 0, runtime: bool = True) -> EvalResult:
    out = []
    for i, s in enumerate(scores):
        out.append(TaskScore(case_id=f"c{i}", trial=0, suite="s", score=s,
                             violations=(CRIT,) * crit if i == 0 else (), tokens_in=tokens // 2,
                             tokens_out=tokens - tokens // 2, wall_ms=wall + 10 * i if runtime else 0.0,
                             llm_calls=calls if runtime else 0, tool_calls=calls // 2 if runtime else 0))
    surface = {} if complexity is None else {"complexity": complexity, "files": 7.0}
    return EvalResult(harness_tree="tree", split="evolve", pin=PIN, scores=out, surface=surface)


def _arm(name: str, ev: EvalResult) -> ArmResult:
    return ArmResult(arm=name, base_commit="inc", head_commit=f"h-{name}", harness_tree=f"t-{name}",
                     edits=[Edit(component="prompt", hypothesis="h", files=("p.md",), commit="c")], eval=ev,
                     status="evaluated", strategy="agent")


def scenarios() -> dict[str, tuple[EvalResult, list[ArmResult], float]]:
    base = [0.5] * 8
    inc = _ev(base)
    return {
        "cost_gain_grows_surface_and_calls": (
            inc, [_arm("a", _ev([0.75] * 8, tokens=110, calls=8, complexity=160.0, wall=3000.0))], 0.125),
        "weighted_token_savings_grows_surface": (
            inc, [_arm("a", _ev(base, tokens=80, complexity=150.0))], 0.125),
        "pure_simplification": (inc, [_arm("a", _ev(base, complexity=60.0))], 0.125),
        "tie_on_score_and_cost_different_complexity": (
            inc, [_arm("a", _ev([0.75] * 8, complexity=150.0)), _arm("b", _ev([0.75] * 8, complexity=80.0))],
            0.125),
        "critical_increase": (inc, [_arm("a", _ev([1.0] * 8, crit=1, complexity=50.0))], 0.125),
        "runtime_and_surface_missing": (
            inc, [_arm("a", _ev([0.75] * 8, runtime=False, complexity=None))], 0.125),
        "in_band_more_calls_and_wall": (
            inc, [_arm("a", _ev(base, tokens=90, calls=12, wall=5000.0)),
                  _arm("b", _ev([0.5] * 7 + [0.25], tokens=70, complexity=90.0))], 0.125),
    }


def decisions() -> dict[str, Any]:
    out: dict[str, Any] = {}
    for prof in PROFILES:
        hp = profile(prof, n_bootstrap=500)
        for name, (inc, arms, delta) in scenarios().items():
            s_star = stats.task_score(stats.index_scores(inc.scores), stats.universe([inc]))
            inp = SelectionInputs(round=1, incumbent=inc, arms=tuple(arms), s_star=s_star, delta=delta, hp=hp)
            out[f"{prof}/{name}"] = select(inp).to_dict()
    return out


def _project(d: dict[str, Any]) -> dict[str, Any]:
    d = dict(d)
    d["arms"] = [{k: v for k, v in a.items() if k not in NEW_ARM_KEYS} for a in d["arms"]]
    d["params"] = {k: v for k, v in d["params"].items() if k not in NEW_PARAM_KEYS}
    return d


@pytest.mark.parametrize("key", sorted(json.loads(GOLDEN.read_text(encoding="utf-8"))))
def test_default_profiles_match_pre_resource_decisions(key):
    golden = json.loads(GOLDEN.read_text(encoding="utf-8"))[key]
    got = json.loads(json.dumps(decisions()[key]))
    assert _project(got) == golden


def test_golden_covers_every_profile_and_scenario():
    golden = json.loads(GOLDEN.read_text(encoding="utf-8"))
    assert set(golden) == {f"{p}/{s}" for p in PROFILES for s in scenarios()}


def test_default_profiles_record_resource_fields_without_gating():
    d = decisions()["local/cost_gain_grows_surface_and_calls"]
    a = d["arms"][0]
    assert a["admissible"] and a["delta_x"] == pytest.approx(0.6) and a["complexity"] == 160.0
    assert a["delta_calls"] > 0 and a["calls_per_task"] == 12.0 and a["wall_ms_p50"] == pytest.approx(3035.0)


def test_tree_invalid_surface_is_inadmissible_under_any_profile():
    inc = _ev([0.5] * 8)
    bad = _ev([0.75] * 8)
    bad = replace(bad, surface={**bad.surface, "tree_valid": 0.0})
    s_star = stats.task_score(stats.index_scores(inc.scores), stats.universe([inc]))
    inp = SelectionInputs(round=1, incumbent=inc, arms=(_arm("a", bad),), s_star=s_star, delta=0.125,
                          hp=profile("local", n_bootstrap=200))
    dec = select(inp)
    assert dec.decision == "do_not_ship" and "tree_invalid" in dec.arms[0].reasons
